### ISSUE TITLE
Index html not in root path

### ISSUE THREAD

**Issue by IniZio** [viko16/vue-ghpages-blog#8]
With `npm run build`, the index html appears in dist directory. Should it be in root directory instead?

**Comment by viko16** [comment]
Hi IniZio, 

The `dist/index.html` is compiled by HtmlWebpackPlguin so I don't need to append `<link>` or `<script>` manually. In my conf, it does output in `dist/` dircectory.

https://github.com/viko16/vue-ghpages-blog/blob/v1.0.0/webpack.config.js#L66-L74

But if you want it be in root directory instead, **just modify the `filename` field**:

``` javascript
    new HtmlWebpackPlguin({
      template: path.resolve(__dirname, 'src', 'tpl.html'),
      filename: '../index.html',   //  <-- then it will output in root directory.
      minify: {
        removeComments: true,
        collapseWhitespace: true
      }
    })
```

**Comment by IniZio** [comment]
yes i did that before posting issue, just want to ask if would change the path for index.html? since the project would be more convenient to have the index.html in root for deploying to github pages

**Comment by IniZio** [comment]
Also such an amazing project to have, i have been scratching my head how to make my blog react with adding/deleting posts, this one separates posts repo and source code, easing the pain of changing content and the blog itself :+1:

**Comment by viko16** [comment]
Thank you IniZio, I am very glad to get your attention. 😄

Actually in the [previous version ](https://github.com/viko16/vue-ghpages-blog/tree/vue-1) `index.html` was placed in root directory because i built then manually.

But now i do a little changes. The contents in `gh-pages` are deployed automatically by [Travis CI](https://travis-ci.org/). 
In this workflow, all files in `dist/` (including `dist/index.html`) would be commited, so i think output all of then into one directory will be better.

**Workflow:**

`npm run build`  ->  output to `dist/`  ->  commit and push to [gh-pages branch](%28https://github.com/viko16/vue-ghpages-blog/tree/gh-pages%29) by TravisCI

https://github.com/viko16/vue-ghpages-blog/blob/develop/.travis.yml#L27-L31

**Comment by IniZio** [comment]
Thanks, the readme misled me to think that it was directly deploy-able though. Might be good if provide the instruction for that also? Closing since the detailed instruction given.

**Comment by viko16** [comment]
@IniZio Yes i will update the readme soom. 😄
